- name: copy pf config
  template:
    src: pf.conf.j2
    dest: /etc/pf.conf
    validate: 'pfctl -n -f %s'
  become: yes

- name: copy pf service config
  copy: 
    src: pf.plist
    dest: /Library/LaunchDaemons/pf.plist
  notify:
    - unload PF service
    - load PF service
