- name: copy pf config
  template:
    src: pf.conf.j2
    dest: /etc/pf.conf
    validate: 'pfctl -n -f %s'
  notify: reload pf

- name: enable pf on boot
  service: name=pf state=started enabled=yes
  # perform this without waiting for the response because PF will drop the
  # SSH connection if its service is not running
  async: 0
  poll: 0
  ignore_errors: true

- name: make sure pf is started
  service: name=pf state=started
