- name: load kernel module
  command: /sbin/kldload pf creates=/dev/pf
  sudo: yes

- name: copy pf config
  template: src=pf.conf.j2 dest=/etc/pf.conf owner=root group=wheel mode=0644
            validate='pfctl -n -f %s'
  sudo: yes
  notify: reload pf

- name: enable pf on boot
  service: name=pf state=started enabled=yes
  sudo: yes

- name: check if pf is enabled
  command: /sbin/pfctl -s info
  sudo: yes
  register: pfctl_info

- name: make sure pf is enabled
  command: /sbin/pfctl -e
  when: |
    "Status: Enabled" not in pfctl_info.stdout
  sudo: yes
